name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components:
        - clippy
        - fmt
        override: true
    #- name: Build
      #run: cargo build --verbose
    - name: Run format
      run: cargo fmt --verbose
    - name: Run Clippy
      run: cargo clippy --verbose
